networks:
  application:
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: base64:6QxqrJj6Rqsx3rmBMsMLN91C/iCIgbBDX5U8cB1uRdE=
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ims_app
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - mysql
      - mailpit
    networks:
      - application
  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ims_app
    networks:
      - application
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root --password=root || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - application
volumes:
  dbdata: